### ISSUE TITLE
It just keep on loading and loading

### ISSUE THREAD

**Issue by Suheb786** [tnesbitt210/interactive-smartlog-issues#13]
**User Report:**

---
**Debug Info:**

*commitTreesLength*: 0

*uncommittedChangesLength*: 20

*outputChannelContents*: 
```
Setup analytics, session:  01efe127-5aa0-4374-ad16-84133a477eaf1718888887123
Operating System: darwin 23.5.0
IGL Version: 0.1.49
Using cached repo info
[track] ClientConnection  
establish client connection for /Users/neosoft/StudioProjects/capital_app_flutter
Using cached repo info
Fetching commits...
Fetching commits...
Fetching commits...
Fetching commits...
[track] FileABug  
```

**Comment by tnesbitt210** [comment]
Thanks @Suheb786 for the info! I have a few questions that would really help me to debug!

1. Is your repo hosted on github? If not, is it another website? (I'd like to try to reproduce your setup, so any info you can share would be helpful).

2. Do you know what the name of the primary remote branch is? (`origin/main`? `origin/master`?)

3: **Could you run `git ls-remote --symref origin HEAD` and let me know what it outputs**? (if your remote is named something other than `origin`, replace `origin` with what ever the name of the remote is). The program looks at the output of this command and tries to find a string like `refs/heads/branchname` (usually branchname is `main` or `master`). I suspect it's missing for you.

Thank you!!

**Comment by tnesbitt210** [comment]
I've also pushed version 0.1.51, which uses a fallback if `git ls-remote --symref origin HEAD` fails.

Would you mind updating to version 0.1.51, and letting me know if the issue still persists? Thanks!
