### ISSUE TITLE
[feature request] Multi-root Workspace Support

### ISSUE THREAD

**Issue by Alecton4** [tnesbitt210/interactive-smartlog-issues#2]
If the first (root) directory opened in a multi-root workspace is not a git repo, the extension will fail to run showing the following message. But other (root) directories in the workspace are valid git repos.

![image](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/43232804/6e44fa1d-398c-40d0-9e4e-ed6ffae4d01d)

**Comment by tnesbitt210** [comment]
Thanks for the report! Should be fixed now in version 0.0.17. Please reopen issue if you still have trouble!
