### ISSUE TITLE
[FR] Allow for subfolder git repo detections

### ISSUE THREAD

**Issue by mathisgauthey** [tnesbitt210/interactive-smartlog-issues#7]
Hey there ! I love the concept, the UI is neat and pretty functional.

My main issue with the plugin in its current state is related to git repo detection.

Currently, the plugin only detects the current folder root directory for `.git` folder. It would be really great if it followed the `Git: Auto Repository Detection` and `Git: Repository Scan Max Depth` used by **Git** and **Source Control** from VSCODE.

**Comment by tnesbitt210** [comment]
Hey @mathisgauthey , thanks for the feedback! I'll look into it :) Just curious - why do you open vscode outside of your git directory?

**Comment by tnesbitt210** [comment]
I pushed something in version 0.0.94! Let me know if it works for you.

**Comment by mathisgauthey** [comment]
> I pushed something in version 0.0.94! Let me know if it works for you.

Yup, that's working now thanks o/
